from datetime import timedelta

SQLALCHEMY_DATABASE_URI = "sqlite:///task_app.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = '5H7Vl7ZZxxioQQPq0IT3T6Hv50zYSoK3WMG0mN6WpJg'
JWT_COOKIE_CSRF_PROTECT = False
JWT_CSRF_CHECK_FORM = False
JWT_CSRF_IN_COOKIES = True
JWT_TOKEN_LOCATION = ['cookies']
JWT_COOKIE_SECURE = False
JWT_ACCESS_COOKIE_PATH = '/api/'
JWT_REFRESH_COOKIE_PATH = '/token/refresh'
JWT_SECRET_KEY = 'hz6CEd6gJOM2hMqrrSCH9sNUl09An0DJsXnD4j05tdc'
JWT_ACCESS_TOKEN_EXPIRES = timedelta(minutes=120)
JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=7)
